spring.application.name=speed-monitor

spring.datasource.url=jdbc:h2:file:~/speeddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true